### ISSUE TITLE
Missing functions when installed using Arduino IDE

### ISSUE THREAD

**Issue by mfreema5** [SMFSW/cQueue#1]
When I installed v1.6 of this library using the Arduino IDE, it did **not** include the function `q_peekIdx`.

I cloned this repository directly, and put it in place of the directory `libraries/cQueue`, and the function is now available and works.

I'm not sure this is a problem the dev here can deal with, but I thought I should record it somewhere.

**Comment by SMFSW** [comment]
Thanks for letting me know!
I'll check that tomorrow.

Usually, Arduino scans for tags in known repositories, but they may have changed their bot behavior about updates. Latest version should be available as I tagged it about 2 weeks ago.

By the way, using Arduino, you may like to try `Queue` library instead (from my repository too), same as cQueue, but maybe a little more convenient in the use (depending how you need to use it) as it's the same implementation using cpp class. Basically, I use cQueue in more critical systems where I only code in c.

I'll post on this issue soon when I'll figure out what happens....

**Comment by SMFSW** [comment]
My mistake, see link beside.

Issue fixed by tagging to a new version.
The updated library should be available in Arduino soon.

Thanks for reporting issue!
