### ISSUE TITLE
Update of last item pushed? 

### ISSUE THREAD

**Issue by matthias-bs** [SMFSW/cQueue#5]
Hi,

my use case is accumulation of daily rainfall data in a FIFO.  
I get the accumulated rainfall data from a sensor at a rate of e.g. 30 minutes. While I'm at the same day as the previous record, I would like to update the last entry pushed to the queue. After the day has changed, I would like to push a new record to the queue.

Two solution come into my mind:
1. Delete previous record (new function: `q_delPrev()`), then push new record
2. Update previous record (new function: `q_update()`)

Is this function of general interest? Which way would you prefer? Any suggestions on the naming?

Thanks in advance!

Regards
Matthias

**Comment by SMFSW** [comment]
Hello,

you probably want to save space, but typically, you would need a second queue for this, one xIFO to accumulate data for a day (or a simple buffer you're averaging on as you acquire new data) and the daily FIFO.

In a queue, once you put an item in it, there's no real reason to change the stored data.
I already had a use case where I needed to reformat the data from a queue; I used 2 queues for this, one to get the "raw" data, and the other one to store the reformated data.

Your `q_delPrev()` function would act somewhat like a LIFO on a FIFO.

I understand your use case, and constraints you may have, but I'm not sure this functionality really belongs to the queue itself.

Let me know what you think,
And sorry for the delay in answering,
Regards,
SMFSW

**Comment by matthias-bs** [comment]
Hello,

you are right, a queue should rather not be overloaded with strange things. ;-)

I will store the current daily amount (which I already get from the sensor) in a separate variable until I finally push it into the FIFO.

Thanks again!

Regards,
Matthias
